### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by deletron247** [freenet-mobile/app#36]
java.lang.NullPointerException: Attempt to invoke virtual method 'void freenet.node.MasterKeys.changePassword(java.io.File, java.lang.String, java.util.Random)' on a null object reference
	at freenet.node.Node.changeMasterPassword(Node.java:4642)
	at freenet.clients.http.SecurityLevelsToadlet.handleMethodPOST(SecurityLevelsToadlet.java:197)
	at java.lang.reflect.Method.invoke(Native Method)
	at freenet.clients.http.ToadletContextImpl.callToadletMethod(ToadletContextImpl.java:747)
	at freenet.clients.http.ToadletContextImpl.handle(ToadletContextImpl.java:660)
	at freenet.clients.http.SimpleToadletServer$SocketHandler.run(SimpleToadletServer.java:1055)
	at freenet.support.PooledExecutor$MyThread.innerRun(PooledExecutor.java:249)
	at freenet.support.PooledExecutor$MyThread.realRun(PooledExecutor.java:189)
	at freenet.support.io.NativeThread.run(NativeThread.java:156)

**Comment by desyncr** [comment]
I guess you got that error while trying to change the master password in settings? Could you describe the steps?
